"""Tutorial-configuration regression tests.

Uses the shared `regression_run` fixture (warm-up + fine restart, defined in
conftest.py) so we share the expensive simulation with the brightness-T
regression test rather than running it twice.

Numerical comparisons (numden, gas_abund) are against time-averaged committed
references in tests/data/regression/spectrum/. These are generated by
tests/generate_spectrum_fixture.py and capture the steady-state distribution
over the ~1000 fine outputs (output_gap=10) post-warm-up. Averaging over the
steady-state fine window — rather than the chaotic warm-up — is what makes
tight tolerances meaningful here.

Byte-equality input-file checks are still compared against
docs/source/notebooks/my_first_carma/inputs/ since those are deterministic
products of the Python config and shouldn't change run-to-run.

Run with `CARMAPY_RUN_INTEGRATION=1 CARMAPY_RUN_SLOW=1`.
"""
import os
import filecmp
from pathlib import Path

import numpy as np
import pytest

REPO_ROOT = Path(__file__).parent.parent.parent
DOCS_REF_DIR = REPO_ROOT / "docs" / "source" / "notebooks" / "my_first_carma"
REGRESSION_REF_DIR = REPO_ROOT / "tests" / "data" / "regression" / "spectrum"

# Tolerances on the time-averaged steady-state quantities. Averaging over the
# ~1000 fine outputs smooths out nucleation-phase noise (single-snapshot
# numden swings 50-80%), revealing the underlying per-cell drift.
NUMDEN_RTOL = 1e-2  # 1% relative
NUMDEN_ATOL = 1.0   # gate out cells with <1 #/cm³ in the reference
GAS_RTOL = 5e-3     # 0.5% relative
GAS_ATOL = 1e-6

DETERMINISTIC_INPUT_FILES = [
    "groups.txt",
    "gases.txt",
    "elements.txt",
    "nucleation.txt",
    "growth.txt",
    "coagulation.txt",
]


@pytest.mark.regression
@pytest.mark.slow
def test_tutorial_creates_output_file(regression_run):
    carma = regression_run
    name = os.path.basename(carma.name)
    assert os.path.exists(os.path.join(carma.name, f"{name}.txt"))


@pytest.mark.regression
@pytest.mark.slow
def test_tutorial_creates_flux_file(regression_run):
    carma = regression_run
    name = os.path.basename(carma.name)
    assert os.path.exists(os.path.join(carma.name, f"flux_{name}.txt"))


@pytest.mark.regression
@pytest.mark.slow
def test_tutorial_numden_regression(regression_run):
    """Time-averaged numden over the fine-restart steady-state window must
    match the committed reference within 1% relative (with atol gating
    near-zero cells).
    """
    ref_path = REGRESSION_REF_DIR / "numden_timeavg.npz"
    if not ref_path.exists():
        pytest.skip(
            f"Numden reference not found at {ref_path}. "
            "Generate with: python tests/generate_spectrum_fixture.py"
        )
    ref = np.load(ref_path)
    new_avg = regression_run.results.numden.mean(axis=-1)
    np.testing.assert_allclose(
        new_avg, ref["numden"],
        rtol=NUMDEN_RTOL,
        atol=NUMDEN_ATOL,
        err_msg=(
            f"Time-averaged numden differs from reference beyond "
            f"{NUMDEN_RTOL*100:.2f}% (atol={NUMDEN_ATOL} #/cm³)"
        ),
    )


@pytest.mark.regression
@pytest.mark.slow
def test_tutorial_gas_abund_regression(regression_run):
    """Time-averaged gas_abund over the fine-restart steady-state window must
    match the committed reference within 0.5% relative.
    """
    ref_path = REGRESSION_REF_DIR / "gas_abund_timeavg.npz"
    if not ref_path.exists():
        pytest.skip(
            f"Gas abundance reference not found at {ref_path}. "
            "Generate with: python tests/generate_spectrum_fixture.py"
        )
    ref = np.load(ref_path)
    new_avg = regression_run.results.gas_abund.mean(axis=-1)
    np.testing.assert_allclose(
        new_avg, ref["gas_abund"],
        rtol=GAS_RTOL,
        atol=GAS_ATOL,
        err_msg=(
            f"Time-averaged gas_abund differs from reference beyond "
            f"{GAS_RTOL*100:.2f}% (atol={GAS_ATOL})"
        ),
    )


@pytest.mark.regression
@pytest.mark.slow
@pytest.mark.parametrize("filename", DETERMINISTIC_INPUT_FILES)
def test_tutorial_input_files_match_reference(regression_run, filename):
    """Python-generated input files should be byte-identical to the committed
    docs reference. Input files are pre-run artifacts of the Python config,
    so they're independent of the simulation's stepping/restart pattern.
    """
    carma = regression_run
    new_file = os.path.join(carma.name, "inputs", filename)
    ref_file = DOCS_REF_DIR / "inputs" / filename
    if not ref_file.exists():
        pytest.skip(f"Reference input file {filename} not found")
    assert filecmp.cmp(new_file, str(ref_file), shallow=False), (
        f"{filename} differs from reference"
    )
