"""Brightness-temperature regression test.

The optimization commits in CARMA are bit-exact at the per-step level but
chaos amplifies them into large per-cell numden differences over many
timesteps. The right observable to gate the regression on is brightness
temperature computed from the *time-averaged* steady-state cloud opacity —
that quantity is robust to nucleation-phase noise and matches the
pre-optimization tutorial-config simulation to ~0.01% (tested empirically
on a614954 vs HEAD).

This test uses the shared `regression_run` fixture (warm-up + fine restart,
defined in conftest.py) and:

  1. Fast path: hash sim.txt and compare to the committed SHA256. If they
     match, the kernel produced bitwise-identical output and the spectrum is
     guaranteed to match the reference — skip the picaso step (saves ~1 min).
  2. Slow path: compute brightness temperature from the picaso spectrum,
     time-averaging the cloud opacity over the full fine window (~1000
     outputs), and assert it agrees with the committed reference within
     0.02% relative.

Run with `CARMAPY_RUN_INTEGRATION=1 CARMAPY_RUN_SLOW=1`. Reference files
are generated by `tests/generate_spectrum_fixture.py`.
"""
import hashlib
import os
from pathlib import Path

import numpy as np
import pytest

REPO_ROOT = Path(__file__).parent.parent.parent
REF_DIR = REPO_ROOT / "tests" / "data" / "regression" / "spectrum"

WAVELENGTHS = np.linspace(1e-5, 2e-3, 10000)
SPECTRUM_R = 1000
TB_RTOL = 2e-4  # 0.02% — the optimization noise floor


def _hash_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


@pytest.mark.regression
@pytest.mark.slow
def test_brightness_temperature_within_tolerance(regression_run):
    """Brightness temperature must agree with the committed reference within
    0.02% relative. Fast-path: if sim.txt hash matches, skip picaso entirely.
    """
    if not (REF_DIR / "Tb_reference.npz").exists():
        pytest.skip(
            "Spectrum reference not found. "
            "Generate with: python tests/generate_spectrum_fixture.py"
        )

    carma = regression_run
    name = os.path.basename(carma.name)
    sim_txt = Path(carma.name) / f"{name}.txt"

    # Fast path: bitwise-equal kernel output → spectrum matches by construction
    new_hash = _hash_file(sim_txt)
    ref_hash = (REF_DIR / "sim.sha256").read_text().strip()
    if new_hash == ref_hash:
        return  # PASS — nothing changed in the kernel

    # Slow path: compute brightness T and compare with tolerance
    picaso_refdata = os.environ.get("picaso_refdata")
    if not picaso_refdata or not Path(picaso_refdata).exists():
        pytest.skip(
            "sim.txt hash differs from reference but picaso_refdata is not "
            "set / not found — cannot run spectrum check. Set the "
            "picaso_refdata env var (and rerun) to validate via tolerance."
        )

    try:
        from picaso import justdoit as jdi
        from picaso import justplotit as jpi
    except ImportError:
        pytest.skip("picaso not installed — cannot run brightness-T tolerance check")

    n_avg = carma.results.numden.shape[-1]

    carma.results.gen_picaso_atm_file()
    carma.results.gen_picaso_cloud_file(WAVELENGTHS, n_avg=n_avg)
    case = jdi.inputs(calculation="browndwarf")
    case.phase_angle(0)
    case.gravity(gravity=carma.surface_grav, gravity_unit=jdi.u.Unit("cm/(s**2)"))
    case.atmosphere(filename=f"{carma.name}/fastchem.atm", sep=r"\s+")
    case.clouds(filename=f"{carma.name}/clouds.atm", sep=r"\s+")
    case.inputs["output_dir"] = None
    opacity = jdi.opannection(wave_range=[0.1, 15])
    df = case.spectrum(opacity, full_output=True, calculation="thermal")
    Tb_new = np.asarray(jpi.brightness_temperature(
        {"wavenumber": df["wavenumber"], "thermal": df["thermal"]},
        R=SPECTRUM_R, plot=False,
    ))
    wno_new, _ = jdi.mean_regrid(df["wavenumber"], df["thermal"], R=SPECTRUM_R)
    wno_new = np.asarray(wno_new)

    ref = np.load(REF_DIR / "Tb_reference.npz")
    Tb_ref = ref["Tb"]
    wno_ref = ref["wavenumber"]

    # Align onto the reference's wavenumber grid (monotonic-ascending interp)
    order = np.argsort(wno_new)
    Tb_on_ref = np.interp(wno_ref, wno_new[order], Tb_new[order])
    rel = np.abs(Tb_on_ref - Tb_ref) / np.abs(Tb_ref)
    max_rel = float(rel.max())
    assert max_rel <= TB_RTOL, (
        f"Brightness T deviates by {max_rel*100:.4f}% from reference "
        f"(tolerance {TB_RTOL*100:.2f}%). "
        f"max |ΔT| = {np.abs(Tb_on_ref - Tb_ref).max():.3f} K. "
        f"Reference range {Tb_ref.min():.1f}-{Tb_ref.max():.1f} K."
    )
